# Generated by Django 2.1.dev20180424160604 on 2018-04-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkt_id', models.CharField(max_length=10)),
                ('greater_than', models.IntegerField(default=0)),
                ('last_bkt', models.IntegerField(default=0)),
                ('init_tax', models.IntegerField(default=0)),
                ('new_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkt_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('greater_than', models.IntegerField(default=0)),
                ('last_bkt', models.IntegerField(default=0)),
                ('init_tax', models.IntegerField(default=0)),
                ('new_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.Federal')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.State')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(max_length=5)),
                ('salary', models.IntegerField(default=0)),
                ('marital_status', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='taxinfo',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.UserInfo'),
        ),
    ]
