# Generated by Django 2.1.dev20180424160604 on 2018-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
