# Generated by Django 2.1.dev20180424160604 on 2018-04-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0002_auto_20180426_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federal',
            name='bkt_id',
        ),
        migrations.RemoveField(
            model_name='federal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='bkt_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AddField(
            model_name='federal',
            name='federal_id',
            field=models.CharField(default=('S', 'single'), max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.CharField(default=('S', 'single'), max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(choices=[('S', 'single'), ('M', 'married')], default='S', max_length=1),
        ),
    ]
