# Generated by Django 2.1.dev20180424160604 on 2018-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_refactored_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(choices=[('S', 'single'), ('M', 'married')], max_length=1),
        ),
    ]
