# Generated by Django 2.1.dev20180424160604 on 2018-04-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0004_auto_20180429_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinfo',
            name='federal',
        ),
        migrations.RemoveField(
            model_name='taxinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='taxinfo',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='TaxInfo',
        ),
    ]
