# Generated by Django 2.1.dev20180424160604 on 2018-05-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0006_auto_20180430_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.IntegerField(default=10016, max_length=5),
        ),
    ]
