# Generated by Django 2.1.dev20180424160604 on 2018-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0007_auto_20180502_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.IntegerField(default=10016),
        ),
    ]
