# Generated by Django 2.1.dev20180424160604 on 2018-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0009_auto_20180503_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=7),
        ),
    ]
